client:
  msg: "Welcome to the climax Dev application"
  build-version: 1

  mailDetails:
    hostName: client@climax.com
    port: 9020
    from: dev-client@climax.com
    subject: "Your clent from climax Dev Environment"