server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          username: 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
          password:
          ignore-local-ssh-settings: true
          uri: https://github.com/sanogosy/climax-config.git
          clone-on-start: true
          default-label: main